plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    mixin {
        defaultRefmapName = "fangsu.refmap.json"
    }
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    modImplementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')

    modImplementation "maven.modrinth:minecraft-transit-railway:$rootProject.mtr_version_fabric"
//    modImplementation "maven.modrinth:jcm:${rootProject.jcm_version_fabric}"
//    implementation 'folk.sisby:kaleido-config:0.3.3+1.3.2'
//    include 'folk.sisby:kaleido-config:0.3.3+1.3.2'
//    if (rootProject.require_nte) {
//        modImplementation "maven.modrinth:mtr-nte:$rootProject.nte_version"
//    }
//    runtimeOnly("org.graalvm.sdk:graal-sdk:${rootProject.graaljsVersion}")
//    runtimeOnly("org.graalvm.truffle:truffle-api:${rootProject.graaljsVersion}")
//    runtimeOnly("org.graalvm.js:js-language:${rootProject.graaljsVersion}")
//    runtimeOnly("org.graalvm.js:js-scriptengine:${rootProject.graaljsVersion}")
//    shadowBundle("org.graalvm.sdk:graal-sdk:${rootProject.graaljsVersion}")
//    shadowBundle("org.graalvm.truffle:truffle-api:${rootProject.graaljsVersion}")
//    shadowBundle("org.graalvm.js:js-language:${rootProject.graaljsVersion}")
//    shadowBundle("org.graalvm.js:js-scriptengine:${rootProject.graaljsVersion}")

    modImplementation "org.graalvm.sdk:graal-sdk:$rootProject.graaljsVersion"
    modImplementation "org.graalvm.truffle:truffle-api:$rootProject.graaljsVersion"
    modImplementation "org.graalvm.js:js-language:$rootProject.graaljsVersion"
    modImplementation "org.graalvm.js:js-scriptengine:$rootProject.graaljsVersion"

    include "org.graalvm.sdk:graal-sdk:$rootProject.graaljsVersion"
    include "org.graalvm.sdk:collections:$rootProject.graaljsVersion"
    include "org.graalvm.sdk:nativeimage:$rootProject.graaljsVersion"
    include "org.graalvm.sdk:word:$rootProject.graaljsVersion"
    include "org.graalvm.polyglot:polyglot:$rootProject.graaljsVersion"
    include "org.graalvm.truffle:truffle-api:$rootProject.graaljsVersion"
    include "org.graalvm.regex:regex:$rootProject.graaljsVersion"
    include "org.graalvm.shadowed:icu4j:$rootProject.graaljsVersion"
    include "org.graalvm.shadowed:xz:$rootProject.graaljsVersion"
    include "org.graalvm.js:js-language:$rootProject.graaljsVersion"
    include "org.graalvm.js:js-scriptengine:$rootProject.graaljsVersion"
}

sourceSets {
    main {
        resources {
            srcDirs += project(':common').sourceSets.main.resources.srcDirs
        }
    }
}


processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_dependency', "~${project.minecraft_version}"
    inputs.property 'fabric_loader_dependency', ">=${project.fabric_loader_version}"
    inputs.property 'architectury_dependency', ">=${project.architectury_api_version}"

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version,
               minecraft_dependency: inputs.properties.minecraft_dependency,
               fabric_loader_dependency: inputs.properties.fabric_loader_dependency,
               architectury_dependency: inputs.properties.architectury_dependency
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'

    exclude 'com/oracle/truffle/**/*Test*'
    exclude 'com/oracle/truffle/**/*Benchmark*'

    mergeServiceFiles()
    zip64 true

//    relocate("org.graalvm", "com.fangsu.shadow.org.graalvm")
//    relocate("com.oracle.truffle", "com.fangsu.shadow.com.oracle.truffle")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    archiveFileName.set("$rootProject.mod_prefix$rootProject.archives_name-mc$project.minecraft_version-${platform}-${rootProject.mod_version}.jar")
}
